epochs: 1000
task: "subs"
name: "gcn"
lr: 0.0001
w_decay: 0.0005
hidden: 100
emb_d: 200
dropout: 0.5
nlayers: 2
val_itr: 100
nr: 10
ntrials: 1
train_batch_size: 1000
val_test_batch_size: 500
margin: 0.5
restartable: True
hydra/launcher: submitit_slurm