epochs: 1000
task: "subs"
name: "gcn"
lr: 0.0001
w_decay: 0.0005
hidden: 50
emb_d: 25
dropout: 0.5
nlayers: 3
val_itr: 100
nr: 1
ntrials: 1
train_batch_size: 1000
val_test_batch_size: 500
margin: 0.7
restartable: True
hydra/launcher: submitit_slurm