hydra:
  run:
    dir: ${checkpoint.dir}/${task}-${ingr_predictor.model}

defaults:
  - dataset: recipe1m
  - image_encoder: resnet50
  - ingr_predictor: ff

task: im2recipe

recipe_gen:
  dropout: 0.5
  embed_size: 2048
  n_att_heads: 8
  layers: 2
  normalize_before: True

optim:
  lr: 0.001
  scale_lr_pretrained: 0.01
  lr_decay_rate: 0.99
  lr_decay_every: 1
  weight_decay: 0.0
  max_epochs: 400
  patience: 10
  loss_weights:
    label_loss: 1.0
    cardinality_loss: 0.0
    eos_loss: 0.0
    recipe_loss: 1.0

checkpoint:
  dir: '/checkpoint/qduval/inversecooking2.0/debug/'
  es_metric: 'o_f1'
  resume_from: None

preprocessing:
  crop_size: 448
  im_resize: 448

misc:
  seed: 1235
  batch_size: 16
  num_workers: 8

recipe1m_pre_processing:
  recipe1m_path: '/checkpoint/qduval/recipe1m/'
  save_path: '/checkpoint/qduval/recipe1m/preprocessed'
  suff: "final_"
  threshold_ingrs: 10  # minimum ingr count threshold
  threshold_words: 10  # minimum word count threshold
  maxnuminstrs: 20  # max number of instructions (sentences)
  maxnumingrs: 20  # max number of ingredients
  minnuminstrs: 2  # min number of instructions (sentences)
  minnumingrs: 2  # min number of ingredients
  minnumwords: 20  # minimum number of characters in recipe
  forcegen: true
