hydra:
  run:
    dir: ${checkpoint.dir}/${task}-${ingr_predictor.model}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - dataset: recipe1m
  - image_encoder: resnet50
  - ingr_predictor: ff
  - slurm: dev

task: im2recipe
executor: local

recipe_gen:
  dropout: 0.5
  embed_size: 2048
  n_att_heads: 8
  layers: 2
  normalize_before: True

optimization:
  seed: 1235
  lr: 0.001
  scale_lr_pretrained: 0.01
  lr_decay_rate: 0.99
  lr_decay_every: 1
  weight_decay: 0.0
  max_epochs: 400
  patience: 10
  loss_weights:
    label_loss: 1.0
    cardinality_loss: 0.0
    eos_loss: 0.0
    recipe_loss: 1.0

checkpoint:
  dir: '/checkpoint/qduval/inversecooking2.0/debug/'
