defaults:
  - dataset: recipe1m
  - ingr_predictor: ff

image_encoder:
  model: "resnet50"
  pretrained: True
  dropout: 0.0
  freeze_pretrained: False

optim:
  lr: 0.001
  scale_lr_pretrained: 0.01
  lr_decay_rate: 0.99
  lr_decay_every: 1
  weight_decay: 0.0
  max_epochs: 400
  patience: 10
  ingr_prediction_loss_weights:
    label_loss: 1.0
    cardinality_loss: 0.0
    eos_loss: 0.0

checkpoint:
  dir: '/checkpoint/adrianars/inversecooking2.0/debug'
  es_metric: 'o_f1'
  resume_from: None

preprocessing:
  crop_size: 448
  im_resize: 448

misc:
  seed: 1235
  batch_size: 10
  num_workers: 8