task: "subs"
name: "gcn"
epochs: 1000
lr: 0.01
w_decay: 0.0005
hidden: 50
emb_d: 25
dropout: 0.5
nlayers: 2
val_itr: 100
nr: 10
ntrials: 1
train_batch_size: 1000
val_test_batch_size: 500
margin: 0.7
max_context: 43
restartable: True