name: "GCN"
setup: "context-full"
epochs: 1000
val_itr: 100
ntrials: 1
train_batch_size: 1000
val_test_batch_size: 100
max_context: 20
margin: 0.7
lr: 0.01
w_decay: 0.0005
hidden: 50
emb_d: 25
dropout: 0.5
nlayers: 2
nr: 10
