name: "MLP"
setup: "context-free"
epochs: 1000
val_itr: 100
ntrials: 1
train_batch_size: 1000
val_test_batch_size: 500
max_context: 0
lr: 0.01
w_decay: 0.0005
hidden: 50
emb_d: 64
dropout: 0.5
nlayers: 2
nr: 400
add_self_loop: False